//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandUpTimer.Specs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StandUpTimer.Specs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the link and create a new user account.
        /// </summary>
        internal static string CreateNewUser {
            get {
                return ResourceManager.GetString("CreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It begins with the sitting phase..
        /// </summary>
        internal static string ItBeginsWithTheSittingPhase {
            get {
                return ResourceManager.GetString("ItBeginsWithTheSittingPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the next startup, the app starts on that position again.
        /// </summary>
        internal static string OnTheNextStartupTheAppStartOnThatPositionAgain {
            get {
                return ResourceManager.GetString("OnTheNextStartupTheAppStartOnThatPositionAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When you entered wrong credentials, you will see an error message and you can retry..
        /// </summary>
        internal static string RetryLoggingIn {
            get {
                return ResourceManager.GetString("RetryLoggingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the app will get into view.
        /// </summary>
        internal static string TheAppWillGetIntoView {
            get {
                return ResourceManager.GetString("TheAppWillGetIntoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribution button.
        /// </summary>
        internal static string TheAttributionButton {
            get {
                return ResourceManager.GetString("TheAttributionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The close button.
        /// </summary>
        internal static string TheCloseButton {
            get {
                return ResourceManager.GetString("TheCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The login button.
        /// </summary>
        internal static string TheLoginButton {
            get {
                return ResourceManager.GetString("TheLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the login dialog in which the register link is.
        /// </summary>
        internal static string TheLoginDialogHasTheRegisterLink {
            get {
                return ResourceManager.GetString("TheLoginDialogHasTheRegisterLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the OK button is visible.
        /// </summary>
        internal static string TheOkButtonIsVisible {
            get {
                return ResourceManager.GetString("TheOkButtonIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The skip button.
        /// </summary>
        internal static string TheSkipButton {
            get {
                return ResourceManager.GetString("TheSkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the time is ticking again.
        /// </summary>
        internal static string TheTimeIsTickingAgain {
            get {
                return ResourceManager.GetString("TheTimeIsTickingAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the skip button.
        /// </summary>
        internal static string UseTheSkipButton {
            get {
                return ResourceManager.GetString("UseTheSkipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait for the time to elapse.
        /// </summary>
        internal static string WaitForTheTimeToElapse {
            get {
                return ResourceManager.GetString("WaitForTheTimeToElapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In case you created a user account, you can now login at the login dialog..
        /// </summary>
        internal static string YouCanLogin {
            get {
                return ResourceManager.GetString("YouCanLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can see how much time is left before changing to another position..
        /// </summary>
        internal static string YouCanSeeTheRemainingTime {
            get {
                return ResourceManager.GetString("YouCanSeeTheRemainingTime", resourceCulture);
            }
        }
    }
}
